language: node_js
node_js:
  - '4'
  - '5'
  - '6'
branches:
  only:
    - master
sudo: false
after_success:
  - npm run coveralls
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
